import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import Footer from "@/component/footer/Footer";
import ClientSideComponentTest from "@/component/clientSideComponentTest";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next.js",
    template: "%s | NextJs 14"
  },
  description: "Generated by create next app description",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideComponentTest>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ClientSideComponentTest>
      </body>
    </html>
  );
}
